name: 'dbt_snfk'
version: '1.0.0'
config-version: 2

profile: 'dbt_snfk'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Seeds configuration
seeds:
  +enabled: true
  schema: SEEDS
  +tags: 
    - SOURCE
    - SEEDS

# Snapshots configuration
snapshots:
  +enabled: false

models:
  # Global project-level configurations
  +packages: ['pandas', 'numpy', 'scikit-learn', 'statsmodels']
  
  # Project structure
  dbt_snfk:
    # Sources are declared and documented in sources.yml
    landing:
      +schema: LANDING
      +materialized: table
    staging:
      +schema: STAGING
      +materialized: table
    mart:
      +schema: MART
      +materialized: table
    reporting:
      +schema: REPORTING
      +materialized: view
