name: 'imp_poc'
version: '1.0.0'
config-version: 2

profile: 'imp_poc'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Seeds configuration
seeds:
  +enabled: true
  schema: SEEDS
  +tags: 
    - SOURCE
    - SEEDS

# Snapshots configuration
snapshots:
  imp_poc:
    +enabled: true
    target_schema: SNAPSHOTS

models:
  # Global project-level configurations
  +packages: ['pandas', 'numpy', 'scikit-learn', 'statsmodels']
  
  # dbt_artifacts package configuration (applies to the dbt_artifacts package models)
  dbt_artifacts:
    +schema: TECH
  
  # Project structure
  imp_poc:
    # Sources are declared and documented in sources.yml
    bronze:
      +schema: BRONZE
      +materialized: table
    silver:
      +schema: SILVER
      +materialized: table
    gold:
      +schema: GOLD
      +materialized: view
