version: 2

models:
  - name: crm_cust_info
    description: "Bronze table for customer information from the CRM source - raw data from source system"
    columns:
      - name: cst_id
        description: "Customer ID"
        data_type: integer
        tests:
          - unique
          - not_null
      - name: cst_key
        description: "Customer key"
        data_type: varchar(255)
        tests:
          - not_null
      - name: cst_firstname
        description: "Customer first name"
        data_type: varchar(100)
      - name: cst_lastname
        description: "Customer last name"
        data_type: varchar(100)
      - name: cst_marital_status
        description: "Customer marital status"
        data_type: varchar(20)
      - name: cst_gndr
        description: "Customer gender"
        data_type: varchar(10)
      - name: cst_create_date
        description: "Customer creation date"
        data_type: date

  - name: crm_prd_info
    description: "Bronze table for product information from the CRM source - raw data from source system"
    columns:
      - name: prd_id
        description: "Product ID"
        data_type: integer
        tests:
          - unique
          - not_null
      - name: prd_key
        description: "Product key"
        data_type: varchar(255)
        tests:
          - not_null
      - name: prd_nm
        description: "Product name"
        data_type: varchar(255)
      - name: prd_cost
        description: "Product cost"
        data_type: integer
      - name: prd_line
        description: "Product line"
        data_type: varchar(100)
      - name: prd_start_dt
        description: "Product start date"
        data_type: timestamp
      - name: prd_end_dt
        description: "Product end date"
        data_type: timestamp

  - name: crm_sales_details
    description: "Bronze table for sales details from the CRM source - raw data from source system"
    columns:
      - name: sls_ord_num
        description: "Sales order number"
        data_type: varchar(50)
        tests:
          - not_null
      - name: sls_prd_key
        description: "Sales product key"
        data_type: varchar(255)
        tests:
          - not_null
      - name: sls_cust_id
        description: "Sales customer ID"
        data_type: integer
        tests:
          - not_null
      - name: sls_order_dt
        description: "Sales order date"
        data_type: integer
      - name: sls_ship_dt
        description: "Sales ship date"
        data_type: integer
      - name: sls_due_dt
        description: "Sales due date"
        data_type: integer
      - name: sls_sales
        description: "Sales amount"
        data_type: integer
      - name: sls_quantity
        description: "Sales quantity"
        data_type: integer
      - name: sls_price
        description: "Sales price"
        data_type: integer

  - name: erp_CUST_AZ12
    description: "Bronze table for customer data from the ERP source - raw data from source system"
    columns:
      - name: CID
        description: "Customer ID"
        data_type: varchar(50)
        tests:
          - unique
          - not_null
      - name: BDATE
        description: "Birth date"
        data_type: date
      - name: GEN
        description: "Gender"
        data_type: varchar(50)

  - name: erp_LOC_A101
    description: "Bronze table for location data from the ERP source - raw data from source system"
    columns:
      - name: CID
        description: "Customer ID"
        data_type: varchar(50)
        tests:
          - not_null
      - name: CNTRY
        description: "Country"
        data_type: varchar(50)

  - name: erp_PX_CAT_G1V2
    description: "Bronze table for product category data from the ERP source - raw data from source system"
    columns:
      - name: ID
        description: "Category ID"
        data_type: varchar(50)
        tests:
          - unique
          - not_null
      - name: CAT
        description: "Category"
        data_type: varchar(50)
      - name: SUBCAT
        description: "Subcategory"
        data_type: varchar(50)
      - name: MAINTENANCE
        description: "Maintenance flag"
        data_type: varchar(50)