version: 2

models:
  - name: example_gold_model
    description: "An example gold layer model - business-level aggregations and insights (view)"
    config:
      materialized: view
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null