-- Create a warehouse
CREATE WAREHOUSE DWH_XS
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
SCALING_POLICY = 'STANDARD';

USE WAREHOUSE DWH_XS;
SHOW WAREHOUSES LIKE 'DWH_XS';

-- Create your database
CREATE DATABASE DWH;

USE DWH;

-- Create your schemas (based on new layer architecture)
CREATE SCHEMA landing;
CREATE SCHEMA staging;
CREATE SCHEMA reporting;