version: 2

models:
  - name: example_silver_model
    description: "An example silver layer model - cleaned and transformed data"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null